### ISSUE TITLE
Arduino.isHigh? rather than Arduino.getState

### ISSUE THREAD

**Issue by Kerrick** [HashNuke/arduino#7]
With ruby, methods that return either `true` or `false` are often named with a question mark. Should `Arduino.getState(pin)` be renamed `Arduino.isHigh?(pin)` instead? Or better yet, to maintain backwards compatibility, you could add it as syntactic sugar and keep the original method name. Bonus points: Add an `Arduino.isLow?(pin)` method.

If you think these are good ideas, I'd be glad to fork the project and make the additions--but I don't have an Arduino I can test with.

**Comment by HashNuke** [comment]
@Kerrick Yes. I wrote this gem when I wasn't using Ruby to write any serious code. The newer version of the gem under development has ruby-ish method names - https://github.com/HashNuke/arduino/tree/development and pending test cases.

**Comment by HashNuke** [comment]
@Kerrick As per the specs I wrote the newer method names are of the form Arduino#higher(), Arduino#high?() and so on

https://github.com/HashNuke/arduino/blob/development/spec/arduino_spec.rb

Thanks for taking a look at this gem and the source code. Appreciate feedback.

**Comment by Kerrick** [comment]
Sweet! I hadn't looked at the development branch. Silly me! :)

**Comment by HashNuke** [comment]
Nah that's fine. Happens to me all the time :) I should have mentioned about the development branch in the README of the repo itself.

Besides, for introductions - my name's Akash
